version: 0.2



phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 614694465844.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t my-nodejs-app .
      - docker tag my-nodejs-app:latest 614694465844.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest
     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 614694465844.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-container","imageUri":"614694465844.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app"}]' 614694465844.dkr.ecr.us-east-1.amazonaws.com/my-nodejs-app > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json
